#!/bin/sh
# mk-readme.sh - generate README index from notes/*.txt
#
# For each note it uses the real title (first line of the file) and the
# date from the "Last Modified:" footer, sorted newest first. No manual
# category lists to keep in sync; the same title+date extraction will
# feed the future RSS/Atom feed.

set -eu

OUT=README
NOTES=notes

cat <<'EOF' > "$OUT"
CODE-NOTES

code-notes is a small collection of concise technical notes.

The notes primarily cover Slackware Linux, Unix system administration,
minimal desktop workflows, package mirrors, QEMU, editors, shell
workflows, and simple tools.

All documents are written in plain text.


DOCUMENTS

NOTE: This list is generated by mk-readme.sh from the notes/ directory,
sorted by last modification (newest first).

EOF

for f in "$NOTES"/*.txt; do
	[ -f "$f" ] || continue

	title=$(head -n 1 "$f")

	date=$(grep '^Last Modified:' "$f" | tail -n 1 \
		| sed 's/^Last Modified:[[:space:]]*//')
	[ -n "$date" ] || date="0000-00-00 00:00:00 UTC"

	printf '%s\t%s\t%s\n' "$date" "$title" "$f"
done \
| sort -r \
| while IFS="$(printf '\t')" read -r date title file; do
	printf -- '  %s  %s\n' "${date%% *}" "$title"
	printf -- '              %s\n\n' "$file"
done >> "$OUT"
