#!/bin/sh
# mk-readme.sh - generate README index from notes/*.txt
#
# For each note it uses the real title (first line of the file) and the
# date from the "Last Modified:" footer, sorted newest first. No manual
# category lists to keep in sync; the same title+date extraction will
# feed the future RSS/Atom feed.

set -eu

OUT=README.md
NOTES=notes
BASE_URL=https://raw.githubusercontent.com/r1w1s1/code-notes/refs/heads/master

cat <<'EOF' > "$OUT"
# code-notes

Plain-text technical notes on Slackware Linux, Unix administration,
minimal desktop workflows, editors, shell tools, and small systems.

The documents are written and maintained as UTF-8 plain text. The Markdown
file is only an index; the `.txt` files are the source documents.

## Documents

This list is generated by `mk-readme.sh` from the `notes/` directory and is
sorted by last modification, newest first.

<pre>
EOF

for f in "$NOTES"/*.txt; do
	[ -f "$f" ] || continue

	title=$(head -n 1 "$f")

	date=$(grep '^Last Modified:' "$f" | tail -n 1 \
		| sed 's/^Last Modified:[[:space:]]*//')
	[ -n "$date" ] || date="0000-00-00 00:00:00 UTC"

	printf '%s\t%s\t%s\n' "$date" "$title" "$f"
done \
| sort -r \
| while IFS="$(printf '\t')" read -r date title file; do
	display_date=${date%% *}
	[ "$display_date" = "0000-00-00" ] && display_date=undated
	printf -- '%s  <a href="%s/%s">%s</a>\n' \
		"$display_date" "$BASE_URL" "$file" "$title"
	printf -- '              %s\n\n' "$file"
done >> "$OUT"

printf '</pre>\n' >> "$OUT"
